### ISSUE TITLE
asciidocLiteralParagraph very slow

### ISSUE THREAD

**Issue by mikepqr** [asciidoc/vim-asciidoc#5]
With `:syntime on` and then `:syntime report`, I get results like this when scrolling down ~10 lines in an asciidoc file:

```
  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  1.974639   2524   0       0.004338    0.000782  asciidocLiteralParagraph \(\%^\|\_^\s*\n\)\@<=\s\+\S\+
  0.949458   2524   0       0.010313    0.000376  asciidocMacroAttributes \(\\\@<!{\w\(\w\|[-,+]\)*\([=!@#$%?:].*\)\?}\)\@<=\S\{-}\[
  0.692648   2524   191     0.002190    0.000274  asciidocMacroAttributes [\\0-9a-zA-Z]\@<!\w\(\w\|-\)*:\S\{-}\[
  0.424680   2524   0       0.005664    0.000168  asciidocDoubleDollarPassthrough \\\@<!\(^\|[^0-9a-zA-Z$]\)\@<=\$\$..\{-}\(\$\$\([^0-9a-zA-Z$]\|$\)\@=\|^$\)
  0.414403   2524   0       0.001611    0.000164  asciidocTriplePlusPassthrough \\\@<!\(^\|[^0-9a-zA-Z$]\)\@<=+++..\{-}\(+++\([^0-9a-zA-Z$]\|$\)\@=\|^$\)
  0.349319   2524   0       0.007933    0.000138  asciidocEmail      [\\.:]\@<!\(\<\|<\)\w\(\w\|[.-]\)*@\(\w\|[.-]\)*\w>\?[0-9A-Za-z_]\@!
  0.219631   2524   0       0.001481    0.000087  asciidocList       .\+\(:\{2,4}\|;;\)$
  0.167563   2524   0       0.002648    0.000066  asciidocURL        \\\@<!\<\(http\|https\|ftp\|file\|irc\):\/\/[^| \t]*\(\w\|\/\)
  0.165062   2461   0       0.001111    0.000067  asciidocHLabel     \(::\|;;\)\(\s\+\|\\$\)
  0.164349   2587   0       0.001767    0.000064  asciidocQuotedEmphasized2 \(^\|[| \t([.,=\]]\)\@<='\([' \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\('\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.160388   2461   0       0.000705    0.000065  asciidocListLabel  \(:\{2,4}\|;;\)$
  0.146719   2713   126     0.000893    0.000054  asciidocQuotedEmphasized \(^\|[| \t([.,=\]]\)\@<=_\([_ \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(_\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.133182   2587   0       0.003897    0.000051  asciidocEntityRef  \\\@<!&[#a-zA-Z]\S\{-};
  0.130972   2587   0       0.002007    0.000051  asciidocQuotedUnconstrainedEmphasized \\\@<!__\S\_.\{-}\(__\|\n\s*\n\)
[snip]
```

That's ~2s to process a regular expression (that in the case of this file never matches). Scrolling is extremely slow and as a result it's very difficult to do without significantly over/undershooting.

I can speed things up by doing `set nocursorline`, which is clearly part of the problem in this case ([and others](http://eduncan911.com/software/fix-slow-scrolling-in-vim-and-neovim.html)), but I get a more significant speedup by simply commenting out this line in asciidoc.vim:

```
syn region asciidocLiteralParagraph start=/\(\%^\|\_^\s*\n\)\@<=\s\+\S\+/ end=/\(^\(+\|--\)\?\s*$\)\@=/ contains=asciidocToDo
```

Can anyone help me understand what that regular expression does? Can it be made more efficient? Should it simply be removed from asciidoc.vim? Given this syntax file is now bundled with vim, Is this something I should report over there?

Bonus question: what's the right way to override it in my vimrc, so I don't have to copy a vim system file into ~/.vim/syntax/? E.g. is threre something like `syn region asciidocLiteralParagraph NONE` I can do in an augroup?

**Comment by elextr** [comment]
>  Given this syntax file is now bundled with vim, Is this something I should report over there?

Yes.

**Comment by mikepqr** [comment]
Thanks. I emailed @srackham, as recommended in vim's [CONTRIBUTING.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md).

**Comment by mikepqr** [comment]
See vim/vim#2539.
